name: Run JMeter Test (Без звіту)

on:
  push:
    branches: [ main ]

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download and extract JMeter
        run: |
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.zip
          unzip apache-jmeter-5.6.3.zip

      - name: Run JMeter
        run: |
          apache-jmeter-5.6.3/bin/jmeter -n -t TaranenkoTest.jmx -l results.jtl
